repos:
- repo: local
  hooks:
  - id: total-java-checkstyle
    name: Checkstyle Requirements
    language: script
    entry: "??"
    files: '^src/'
    types: [file, java]
  - id: unit-test
    name: Implement Unit Testing for Feature
    language: system
    entry: "??"
    always_run: true
    pass_filenames: false
  - id: integration-test
    name: Implement Integration Testing for Feature
    language: system
    entry: "??"
    always_run: true
    pass_filenames: false
  - id: main-linting
    name: Format Main Engine code
    entry: ./format.sh
    # stages: [manual]
    language: script
    files: '^src/main'
    types: [file, java]
    pass_filenames: false
    args: ['src/']
  - id: test-linting
    name: Format Main Engine Testing code
    language: script
    entry: ./format.sh
    files: '^src/test/'
    types: [file, java]
    pass_filenames: false
    args: ['src/']


  # TODO: Will implement it later
  # - id: docs
  #   name: Format documentation
  #   stages: [manual]
  #   language: node
  #   language_version: 20.5.0
  #   entry: prettier --write --list-different --ignore-unknown README.md
  #   "types": [text]
  #   files: 'README.md'
  #   pass_filenames: false
  #   additional_dependencies:
  #     # When updating the version of prettier, make sure to check the  pre-commit file
  #     # And keep the `entry` here up to date https://github.com/pre-commit/mirrors-prettier/blob/master/.pre-commit-hooks.yaml
  #     - prettier@3.0.0
